### ISSUE TITLE
Componente PlayerController

### ISSUE THREAD

**Issue by NachoDelCastillo** [P3-22-23-Grupo6/Juego-De-Autos#1]
- [ ] Utilizar Input Manager para el control del coche, con parametros de velocidad, aceleracion, veolcidad maxima, etc.
- [ ] Crear un Raycast para igualar la direccion del suelo en todo momento

**Comment by NachoDelCastillo** [comment]
Usando el InputEngine, crear un componente que tenga la habilidad de acelerar, girar y frenar segun esta especificado en el GDD

**Comment by ivo-hr** [comment]
Ahora mismo esto es dependiente de [este bug](https://github.com/P3-22-23-Grupo6/Motor/issues/73), trabajando en el bug primero
